<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_LOGIN_addressInfoFrame</name>
   <tag></tag>
   <elementGuidId>4d0841ac-31f4-4432-b7e9-0d3162fbb4fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addressInfoFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='addressInfoFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e55a8048-a6a8-47d1-a584-6289480404d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressInfoFrame</value>
      <webElementGuid>ad628f9f-8c66-45a3-a844-a5662c9fdb37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>learnks1-frame2.html</value>
      <webElementGuid>f7c67c03-fe17-4b5a-9f61-32f019eac163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>5ca71bd1-47b5-4432-affc-81e4e8fcd40f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>8fe801d2-4b5a-42ae-b5d5-046824ed8c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressInfoFrame&quot;)</value>
      <webElementGuid>5a3fa1cc-bf80-46d9-b2b2-a29a0470f24b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='addressInfoFrame']</value>
      <webElementGuid>4cb7b865-4dee-4347-8cc6-259cbf18201b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/iframe</value>
      <webElementGuid>14cf5311-84b4-423a-ae7f-5b6cefed457b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'addressInfoFrame' and @src = 'learnks1-frame2.html']</value>
      <webElementGuid>aeed9088-7842-42c2-9cf3-5017016ec4f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
