<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Street Address</name>
   <tag></tag>
   <elementGuidId>731a8b2b-3508-44e8-910b-fb03c13f78fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#streetAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='streetAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7d34839-bb15-45ed-b0b4-f97a488b8282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>70fa3fda-eb0c-43fd-998c-3840f75ffc7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>streetAddress</value>
      <webElementGuid>b9ee49ab-e6a2-4d7b-b693-038a99d4c6a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;streetAddress&quot;)</value>
      <webElementGuid>8cfeb263-ed9c-4adb-b77c-efbbb4d1c7ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Window iFrame Alert/Home Page/iFrame 2/iframe_LOGIN_addressInfoFrame</value>
      <webElementGuid>d9d2cfdb-8b82-476f-bb79-2b0db7406d23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='streetAddress']</value>
      <webElementGuid>cfcc7df3-c7dd-40a0-a440-28a2c77d79e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4dd75672-6f7e-47e7-a438-526a9d446a83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'streetAddress']</value>
      <webElementGuid>649b8276-44a6-4a1f-bd2f-e4a27eb8d537</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
