<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Forgotten Password_emailAddress</name>
   <tag></tag>
   <elementGuidId>f0a1be9c-da9f-4bbd-af58-814bda3648dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emailAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emailAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>805d9a3c-3e52-4283-b51f-27c19569a2b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>117e2444-fe72-40ce-888f-e07cb19ec565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emailAddress</value>
      <webElementGuid>246da3de-4105-41dd-ab96-9e2a68ff98de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emailAddress&quot;)</value>
      <webElementGuid>a051e5ae-c7ac-46c2-9f8a-db3a661a3d8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emailAddress']</value>
      <webElementGuid>9ce425e2-f5a8-45b6-b204-615d90963884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='forgotPasswordForm']/p[2]/input</value>
      <webElementGuid>07fd732e-1e32-4e61-a921-d110fdc6b8c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>42cf6b75-7f2a-4be3-b6c0-259334e13059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'emailAddress']</value>
      <webElementGuid>78c5c7a1-4a47-449e-8ca7-1dffa10ad5d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
