<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Check_Communicator</name>
   <tag></tag>
   <elementGuidId>f7c9515a-caae-44c3-9a4d-007fa886f465</elementGuidId>
   <imagePath>https://adminonline.biz/AdminOnline//version/10.1/isomorphic/skins/IITS/images/DynamicForm/checked.png</imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@tabindex='2027']/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[@eventpart = 'valueicon' and @type = 'checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_8W</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>https://adminonline.biz/AdminOnline//version/10.1/isomorphic/skins/IITS/images/DynamicForm/checked.png</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a056b22c-2606-4b42-9e8c-acc8156f2b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_8W</value>
      <webElementGuid>1f360d36-5ac1-4f11-b0d5-18c5d48d55bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>eventpart</name>
      <type>Main</type>
      <value>valueicon</value>
      <webElementGuid>76fe48ab-580a-482e-abf3-65fb3d62141a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_8W&quot;)</value>
      <webElementGuid>ca7c2f7d-6480-4f80-8b8b-e26041bad542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5bebb360-2c55-4080-ac8a-8774958e1fac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='isc_8W']</value>
      <webElementGuid>9e57508b-f7de-4b6d-abc4-ebaea34fd2b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_8V']/span</value>
      <webElementGuid>09273638-13b3-4a72-a695-639d438466b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/table/tbody/tr/td/div/span</value>
      <webElementGuid>f26a1983-49d4-4b2e-a53b-a20b2c470d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'isc_8W']</value>
      <webElementGuid>a11355ab-2418-4da4-8f97-9e82fb3788bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
