<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown option_Send By Email</name>
   <tag></tag>
   <elementGuidId>389640b3-bf61-45a2-8f85-71c5ea297036</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='isc_PickListMenu_5_row_1']/td/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@role = 'presentation' and @cellclipdiv = 'true' and (text() = 'Send By Email' or . = 'Send By Email')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.pickListCellSelectedDark > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1a016e24-38d7-4736-85bd-9a21cd09d5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>aafafa18-16d3-428e-bd83-d95a2f269db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cellclipdiv</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0d4504e0-335a-4e93-a19b-627ae975b6e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send By Email</value>
      <webElementGuid>ecca9d67-53c0-4a32-9f3c-1739a7d48d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_PickListMenu_5_row_1&quot;)/td[@class=&quot;pickListCellSelectedDark&quot;]/div[1]</value>
      <webElementGuid>21bba50d-e886-47f6-a49f-bafa4d7c1683</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='isc_PickListMenu_5_row_1']/td/div</value>
      <webElementGuid>35b271ba-d5ff-40a3-b78b-d93a708815d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send By Both Email and SMS'])[1]/following::div[1]</value>
      <webElementGuid>cdafc3e6-f37f-469c-b84a-0e19d5735aee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Status'])[1]/following::div[12]</value>
      <webElementGuid>1a179045-49cf-41b3-9e13-1fbf03596cc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send By SMS'])[1]/preceding::div[1]</value>
      <webElementGuid>1e6e421e-9e49-40c4-bfea-895b8c626361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Send By Email']/parent::*</value>
      <webElementGuid>c31b79cc-6daf-4e30-9e37-b287f626a028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/div/div/div/table/tbody/tr[2]/td/div</value>
      <webElementGuid>0150b14b-1ee0-48b8-89ce-c4378b40fbc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Send By Email' or . = 'Send By Email')]</value>
      <webElementGuid>0b944d3f-31d0-4d45-ab59-5edc2f3757d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
