<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Charge</name>
   <tag></tag>
   <elementGuidId>2445e0d1-200c-4ef8-bdee-fb64c6ae4a1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body//div[text()='Charge']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_8J</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8f619499-8438-47e8-9ab7-c21f0902e8bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_8J</value>
      <webElementGuid>4cb056dc-0d2d-4b08-9ebf-d8e7c94db8be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Charge</value>
      <webElementGuid>469083c9-bf1c-404f-852d-4a37b3f6111a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_8J&quot;)</value>
      <webElementGuid>3e262749-e944-4f48-8269-0c512d526a55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_8J']</value>
      <webElementGuid>38000a78-b1e6-416f-8e72-00b4a182f538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_8K']/table/tbody/tr/td/div</value>
      <webElementGuid>3fa268e6-33c9-48d6-a967-3d12702511be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[4]/following::div[2]</value>
      <webElementGuid>f84b9ec0-a8a0-438c-9a7c-8a14d9ac4f98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service Name'])[1]/following::div[7]</value>
      <webElementGuid>f0bfa53f-5ee0-40fc-906f-c5d2580c3f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic Billing Annually'])[1]/preceding::div[5]</value>
      <webElementGuid>61cf92b3-db50-4c04-9f6c-631771c837fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic Billing Monthly'])[2]/preceding::div[6]</value>
      <webElementGuid>4b0a8a72-ebaf-4f11-94c6-c8e74e528c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Charge']/parent::*</value>
      <webElementGuid>ca831a51-4fe7-45ef-b32f-ec684c149c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/div[2]/table/tbody/tr/td/div</value>
      <webElementGuid>8a8c1f47-3393-4c54-acfa-8b17eef9e88c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_8J' and (text() = 'Charge' or . = 'Charge')]</value>
      <webElementGuid>c70ff3d5-0f67-430e-a9ad-004eccc8f876</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
