<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Calendar_Month</name>
   <tag></tag>
   <elementGuidId>95188cac-e62e-4188-9cb7-4ff6a439146f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_7I</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='isc_7I']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>17b2b9bc-e366-4e3d-8f65-7d4ee38308ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_7I</value>
      <webElementGuid>b03cbb6d-f582-441c-a404-804147097ea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$89</name>
      <type>Main</type>
      <value>isc_SelectItem_1</value>
      <webElementGuid>337fd110-dbf2-4387-addd-f36f7b252b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$9a</name>
      <type>Main</type>
      <value>$9d</value>
      <webElementGuid>0a699c73-f280-47b3-823b-c06b0817216f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectItemTextFocused</value>
      <webElementGuid>5f4e40cc-ca04-4bce-baca-08e584aa9a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4727</value>
      <webElementGuid>68a35f20-bbf2-465d-8209-440235ffe0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>951ac10f-6c92-41ae-be5e-7080c06ff36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>May</value>
      <webElementGuid>0a04b910-2c10-4f93-bea3-6bf3df4f4642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_7I&quot;)</value>
      <webElementGuid>602a6054-63d8-4bff-bc32-3d7d6a0f00c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_7I']</value>
      <webElementGuid>0637bbed-bf51-4139-8f3a-fe742369eadb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_7H']/tbody/tr/td/div</value>
      <webElementGuid>4a2dd60c-2eb8-437c-ae8e-bfef2dc0be03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Initiate Billing For Selected Service'])[1]/following::div[8]</value>
      <webElementGuid>dbfb10a1-1ecf-4837-9ee2-010fa17054a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing Category'])[1]/preceding::div[2]</value>
      <webElementGuid>290efc78-ad04-4d16-a2e8-4e0f0f9aee10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From Date in Description'])[1]/preceding::div[3]</value>
      <webElementGuid>4c8cfd0b-6cc7-41a5-95cd-62011e1aef3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='May']/parent::*</value>
      <webElementGuid>75b6a3b5-4e7c-49da-9d99-dd1a2840eeea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/div</value>
      <webElementGuid>1a57b536-d183-4bbd-b467-388a4b977b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_7I' and (text() = 'May' or . = 'May')]</value>
      <webElementGuid>3747b541-65cb-48c3-9a29-7212ab8e8633</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
