<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>check_Service Name_Index_0</name>
   <tag></tag>
   <elementGuidId>b2276c97-0b5d-4b49-ab22-0d639a9dc546</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='isc_PickListMenu_1_row_0']/td/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_95</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>82207bd6-33ee-4bf5-9ba7-2414ad84ac5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_95</value>
      <webElementGuid>53da8d88-8d0d-4889-afeb-bcfd6337a597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>eventproxy</name>
      <type>Main</type>
      <value>isc_PickListMenu_1</value>
      <webElementGuid>5c5794b2-17f6-4b1f-84f5-2949f9378ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>ccf6bc2e-7148-45bf-b64e-41bf0c8a85df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>listGrid</value>
      <webElementGuid>a811c49c-0cc7-43eb-a504-61c5dc291da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onscroll</name>
      <type>Main</type>
      <value>return isc_PickListMenu_1.$lh()</value>
      <webElementGuid>e3881d80-52b4-49ed-8fba-793ebe9650f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>88a46f1a-6012-4a9b-915b-105e36f76ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 2 - Quarterly Fee2021 MonthlyGodwin TennisJump and SkipKiddies clubMonthly FeeNew servicePackage 24 - Pm over over 2 monthsPackage 24 Pm over 3 monthsPackage 24 Pm over 4 monthsplay Softball once a weekPlayball Monthly FeeSwimming x1 a week - TermlySwimming x2 a week - TermlyTennis x1 a weekTennis x2 a week</value>
      <webElementGuid>a50c4c5d-cd8a-4e5d-a4f7-532b6a58cf14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_95&quot;)</value>
      <webElementGuid>97ace31d-3ec7-4d8a-ab3f-56eabfa9872e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_95']</value>
      <webElementGuid>4e56f6d4-8ace-4ff8-86e0-5e3ce605a015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Charge'])[1]/following::div[4]</value>
      <webElementGuid>2f4c3c4a-2cfd-4259-8761-6d063f0f9b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[4]/following::div[6]</value>
      <webElementGuid>1089ae44-d2bd-404f-8c5c-4890806acb27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]</value>
      <webElementGuid>911e59a6-e69f-464f-b097-4ca56ab27f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_95' and (text() = ' 2 - Quarterly Fee2021 MonthlyGodwin TennisJump and SkipKiddies clubMonthly FeeNew servicePackage 24 - Pm over over 2 monthsPackage 24 Pm over 3 monthsPackage 24 Pm over 4 monthsplay Softball once a weekPlayball Monthly FeeSwimming x1 a week - TermlySwimming x2 a week - TermlyTennis x1 a weekTennis x2 a week' or . = ' 2 - Quarterly Fee2021 MonthlyGodwin TennisJump and SkipKiddies clubMonthly FeeNew servicePackage 24 - Pm over over 2 monthsPackage 24 Pm over 3 monthsPackage 24 Pm over 4 monthsplay Softball once a weekPlayball Monthly FeeSwimming x1 a week - TermlySwimming x2 a week - TermlyTennis x1 a weekTennis x2 a week')]</value>
      <webElementGuid>ecee201f-19ab-49cb-9b46-d9fc3db5e595</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
