<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>drop_Service Name_option_index_0</name>
   <tag></tag>
   <elementGuidId>ee317254-fd30-4c83-a67d-2eaf7e949ddb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='isc_PickListMenu_1_row_0']/td[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>825660fa-7c13-4903-8730-7aea58cd920b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>2746e067-bab2-48d7-ad03-10c21bc62093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cellclipdiv</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>02a1fff9-436d-4222-960b-3a4750371dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>01 Sample Monthly Service</value>
      <webElementGuid>4c7ef94e-23e2-42aa-9968-28c4d7e7e350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_PickListMenu_1_row_0&quot;)/td[@class=&quot;pickListCellOver&quot;]/div[1]</value>
      <webElementGuid>59847301-466b-49c6-87e4-c89c3392766e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='isc_PickListMenu_1_row_0']/td[2]/div</value>
      <webElementGuid>d0c393aa-8c4c-4b7d-8c46-2df293b16347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic Billing Semester'])[1]/following::div[10]</value>
      <webElementGuid>5d358cf5-c03c-4080-91b8-e870bb8990cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic Billing Quarterly'])[1]/following::div[11]</value>
      <webElementGuid>f5f43238-a5ac-49c1-9daf-e1ea0f24c53f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div/div/div/table/tbody/tr/td[2]/div</value>
      <webElementGuid>6ab8daaa-a091-4282-8052-a5278de2de46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '01 Sample Monthly Service' or . = '01 Sample Monthly Service')]</value>
      <webElementGuid>5173a05d-b0ce-432b-aa4d-69020fb6fa06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
