<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>drop_arrow_Service Name</name>
   <tag></tag>
   <elementGuidId>70676533-57b9-4532-9568-14ac6148e82d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_87</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='isc_87']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f65d17f5-42cc-44e4-8442-77ed7d05a191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://adminonline.biz/AdminOnline//version/10.1/isomorphic/skins/IITS/images/blank.gif</value>
      <webElementGuid>dfc46fa5-6bd0-43a0-9aa7-234c58183a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>cc2753b0-56b2-4233-88eb-a31884749454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>d5e368a7-2b88-44c8-9213-7410b65051eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>absmiddle</value>
      <webElementGuid>77a76155-0f3b-4008-bbf5-7ca18454b909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>comboBoxItemPicker</value>
      <webElementGuid>ac136011-f1ec-4212-82f8-f4830c8b8430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_87</value>
      <webElementGuid>33150663-7dab-40af-8df5-31900f30a92e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e65e1407-f191-4d92-aad5-126baff73182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>suppress</name>
      <type>Main</type>
      <value>TRUE</value>
      <webElementGuid>69705ea2-ed32-47fa-88dd-dcf9c162acae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2acb0092-3ca6-48a5-abe9-2a97c410bbee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_87&quot;)</value>
      <webElementGuid>ab0c0a7d-c75f-4393-9366-731644a50e2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='isc_87']</value>
      <webElementGuid>5a972881-14f9-41e0-a35a-6225211c4c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='isc_86']/img</value>
      <webElementGuid>58041319-6dad-4c63-b565-073bb13b07c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://adminonline.biz/AdminOnline//version/10.1/isomorphic/skins/IITS/images/blank.gif')])[27]</value>
      <webElementGuid>c4c828d2-4d9a-43e0-abb5-8854503d0a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/table/tbody/tr/td/table/tbody/tr/td[2]/span/img</value>
      <webElementGuid>2aa45034-08f6-404c-9df4-e184df048e20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://adminonline.biz/AdminOnline//version/10.1/isomorphic/skins/IITS/images/blank.gif' and @id = 'isc_87']</value>
      <webElementGuid>cd2dc139-ddad-49bf-8100-1f84d94c46a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
