<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>drop_arrow_Billing Category</name>
   <tag></tag>
   <elementGuidId>59c07ba1-2795-42a7-b98d-ef4d3c733277</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_7G</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='isc_7G']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>95977492-647a-468a-ba9e-d6114a028aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://adminonline.biz/AdminOnline//version/10.1/isomorphic/skins/IITS/images/blank.gif</value>
      <webElementGuid>fdf58aa6-b0f3-4da2-98c7-45ed084b5e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>431e9acb-60ec-48d5-936e-f2172092e042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>81c85722-d41d-4fa1-bb19-b197f51038cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>absmiddle</value>
      <webElementGuid>735a370e-79c7-4772-9a44-6e984d1a141c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>comboBoxItemPicker</value>
      <webElementGuid>1ddc516a-34a9-4730-9d65-be4eeedeb440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_7G</value>
      <webElementGuid>91aac328-d613-4182-abd1-d7844cc4157f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>810ed13e-9613-4df4-82e6-5cd676fddb39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>suppress</name>
      <type>Main</type>
      <value>TRUE</value>
      <webElementGuid>a05172c1-544b-4b41-b7ce-260c4305c6f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e35091e0-af76-4d41-9319-4d17d4cf737a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_7G&quot;)</value>
      <webElementGuid>41e1552c-9c34-4d33-a39f-43bcfc8c7cbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='isc_7G']</value>
      <webElementGuid>1a2536bf-967f-49cf-9444-7a42a509ac5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='isc_7F']/img</value>
      <webElementGuid>402c73a4-7489-44b3-bfc9-794cfd7df189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://adminonline.biz/AdminOnline//version/10.1/isomorphic/skins/IITS/images/blank.gif')])[26]</value>
      <webElementGuid>0c307cdb-dfc8-44ba-8611-952883b8de4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/table/tbody/tr/td[2]/span/img</value>
      <webElementGuid>0a401978-0d43-4359-94de-b2df9ec2036d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://adminonline.biz/AdminOnline//version/10.1/isomorphic/skins/IITS/images/blank.gif' and @id = 'isc_7G']</value>
      <webElementGuid>992405d5-87cd-4f0d-b801-97be3a893f28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
