<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iFrame_Service Name</name>
   <tag></tag>
   <elementGuidId>15d216a2-8734-42e5-b799-33f9d52ed0ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body//div[@tabindex='4635']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_7Y</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>56088070-311a-44a8-81cc-140befd654b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_7Y</value>
      <webElementGuid>a6c933a6-4ce7-495c-a0e6-ee34de6c8b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$89</name>
      <type>Main</type>
      <value>isc_SelectItem_4</value>
      <webElementGuid>ad2347cb-5ee2-4914-8299-a7aa85908c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$9a</name>
      <type>Main</type>
      <value>$9d</value>
      <webElementGuid>1f0cd3e0-7a39-4ed9-9a87-5c01cae07251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectItemTextFocused</value>
      <webElementGuid>02d96e36-4c40-4832-9f8a-7b86b095ea14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4476</value>
      <webElementGuid>aefab50a-db3f-4744-b669-c69f84812709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f0d0a013-be57-46f2-bffc-29ef9bd9fb1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2021 Monthly, Monthly Fee, Package 24 Pm over 3 months</value>
      <webElementGuid>d8b9bd87-e308-4f62-a88e-586830ef6694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_7Y&quot;)</value>
      <webElementGuid>1a3e85fa-2cb8-4a5a-a9b0-abfd1ae2956b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_7Y']</value>
      <webElementGuid>ccf63905-88a9-4639-b97e-9a4fd50f2747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_7X']/tbody/tr/td/div</value>
      <webElementGuid>2a1c5cfc-7a68-454d-ab03-d7456ec304bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service Name'])[1]/following::div[1]</value>
      <webElementGuid>8b3feadc-b51a-4ef5-aa57-56c6ecea19af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To Date in Description'])[1]/following::div[1]</value>
      <webElementGuid>b4d4f15f-0a15-4790-9539-0bff792a35a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[4]/preceding::div[1]</value>
      <webElementGuid>4f330141-674d-4306-ad83-e5bee011212b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Charge'])[1]/preceding::div[3]</value>
      <webElementGuid>32cd9dce-36d4-4ace-9b12-801738b20149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2021 Monthly, Monthly Fee, Package 24 Pm over 3 months']/parent::*</value>
      <webElementGuid>452fcd6c-cd2c-411e-a49d-846b336a111d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/table/tbody/tr/td/table/tbody/tr/td/div</value>
      <webElementGuid>a9206784-6bfc-401a-9a88-86235b64dea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_7Y' and (text() = '2021 Monthly, Monthly Fee, Package 24 Pm over 3 months' or . = '2021 Monthly, Monthly Fee, Package 24 Pm over 3 months')]</value>
      <webElementGuid>210572fc-2957-4dde-9301-ebd400381871</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
