<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_From Date Description</name>
   <tag></tag>
   <elementGuidId>ae99f526-490d-4dee-b12f-eec0b0d2987f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_7I</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='isc_7I']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78ed5838-4568-441e-9826-0e3eac332161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>451d1c54-20fb-47c8-a877-00a44cebef6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>inv_service_from_d_dateTextField</value>
      <webElementGuid>d98e8477-ad1a-4ce0-b2ad-fa5edb5427d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_7I</value>
      <webElementGuid>634a15d8-9d4d-45f5-ac85-13d846ea73ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>handlenativeevents</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ac0d37ff-b735-4824-9541-5974c8d37b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$89</name>
      <type>Main</type>
      <value>isc_TextItem_2</value>
      <webElementGuid>ffa6316a-cfb4-48c4-acdd-73743863f7ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$9a</name>
      <type>Main</type>
      <value>$9b</value>
      <webElementGuid>efe4b62c-dd99-4449-bf28-8016088eb0b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3935651e-b4c7-4162-a99e-2928b03b0334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>isc_TextItem_2._handleInput()</value>
      <webElementGuid>2c827d3d-55a3-4dc5-a82b-38213605764d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onselect</name>
      <type>Main</type>
      <value>if (window.isc_TextItem_2 == null) return;isc_TextItem_2.$1162()</value>
      <webElementGuid>1aa93262-01b9-4cf6-b1fe-25b5105aa7fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>OFF</value>
      <webElementGuid>7696c911-0a15-4a62-8e9d-1a987de73b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textItem</value>
      <webElementGuid>19359317-819e-4fd0-87ca-54d18fa25ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4474</value>
      <webElementGuid>b2c02ec8-7b4a-4c68-9d1b-a23d0851ef89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_7I&quot;)</value>
      <webElementGuid>7b5dcbda-57b0-479d-8279-c4359ff8cf02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isc_7I']</value>
      <webElementGuid>8305a070-982b-42fe-b7b9-4628476dcd56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='isc_7L']/input</value>
      <webElementGuid>67c900c9-4414-4bda-9021-077a526f1324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>7ccbdd82-4a10-4705-96b1-1c1f1223511f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'inv_service_from_d_dateTextField' and @id = 'isc_7I']</value>
      <webElementGuid>1def932d-eaa7-4de1-bd0c-31cefb2d968b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
