<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>popup_Add Bulk Billing</name>
   <tag></tag>
   <elementGuidId>baa7f273-3acb-47a3-adc8-b010cde56287</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='isc_DB']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_DB</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>73ba36c5-e683-4c71-973f-98f7b95a7981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_DB</value>
      <webElementGuid>521c299a-8113-41f8-9210-2fe399e82710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>eventproxy</name>
      <type>Main</type>
      <value>winManualActivityBilling</value>
      <webElementGuid>e4c963d2-b5fe-4b1a-802f-af9a544ab7af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>windowBackground</value>
      <webElementGuid>49cc5b6a-5cd7-49d8-acb3-34ffb1166c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onscroll</name>
      <type>Main</type>
      <value>return winManualActivityBilling.$lh()</value>
      <webElementGuid>80ba4c81-ef9f-46e6-9e78-456a2c5646fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>d887eb13-4488-4e44-a71d-c904a44e41b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>isc_DC</value>
      <webElementGuid>e3572c43-27b0-4be3-978d-6cca0bd2da79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>isc_DD</value>
      <webElementGuid>0b10ccf5-dead-4ceb-9455-7eef75083ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>    Basic Billing ChargeBasic Billing Charge  Initiate Billing For Selected Service Invoice Date :2022May19Billing Category :Basic Billing MonthlyFrom Date in Description :To Date in Description :Service Name : CloseCharge </value>
      <webElementGuid>d0bb80ff-c5ad-4797-ae5f-b3363c0ebe88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_DB&quot;)</value>
      <webElementGuid>74845d80-35d2-4a14-b5c4-ce82c326c1ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_DB']</value>
      <webElementGuid>67c868d2-c1ef-49ab-972a-2ed256bf0b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No items to show.'])[1]/following::div[11]</value>
      <webElementGuid>624cd148-547d-4961-8f42-058c8e089b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type'])[1]/following::div[13]</value>
      <webElementGuid>0961b0ef-b88e-47ec-9d0a-613c3ce31118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]</value>
      <webElementGuid>5d4cbe43-6f3b-4fa1-9e92-0e851051ded3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_DB' and (text() = '    Basic Billing ChargeBasic Billing Charge  Initiate Billing For Selected Service Invoice Date :2022May19Billing Category :Basic Billing MonthlyFrom Date in Description :To Date in Description :Service Name : CloseCharge ' or . = '    Basic Billing ChargeBasic Billing Charge  Initiate Billing For Selected Service Invoice Date :2022May19Billing Category :Basic Billing MonthlyFrom Date in Description :To Date in Description :Service Name : CloseCharge ')]</value>
      <webElementGuid>354d598e-94e1-41d4-b07b-263dc1ac0bb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
