<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Close</name>
   <tag></tag>
   <elementGuidId>7d0088fa-1b8c-4e2c-ac4a-a6d7d6358f10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_3E</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='isc_3E']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ebd71380-963c-4235-8af0-a0c7c60e89b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_3E</value>
      <webElementGuid>d4092228-6c62-43aa-b2ce-9eb571e3ac23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>dc61927a-cce4-499a-b722-4862462e1d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_3E&quot;)</value>
      <webElementGuid>bffbe17c-2fbd-47c1-bc8f-1ca137efb9cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_3E']</value>
      <webElementGuid>344e7c9b-0639-4a09-88fe-4f98fb571fdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_3F']/table/tbody/tr/td/div</value>
      <webElementGuid>7463fbad-413b-488c-8471-f181f69cb0e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Bulk Billing / Invoicing (Basic &amp; Advanced)'])[1]/following::div[6]</value>
      <webElementGuid>680178e0-bae6-4a06-9210-0aeb973b4396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulk Billing / Invoicing'])[2]/following::div[11]</value>
      <webElementGuid>fa504072-1533-4017-9ef4-fd188be6c1f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Billing Run'])[1]/preceding::div[1]</value>
      <webElementGuid>851cf715-8fe6-4e8a-a7a4-111762fcae5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete Billing Run'])[1]/preceding::div[3]</value>
      <webElementGuid>1fe56fe2-cb00-41bb-b61b-0cd57349ffc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div</value>
      <webElementGuid>596b8a48-4e1b-45ae-b2ef-fddb54af4ae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_3E' and (text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>273bc54e-5aaf-4ad6-8234-962aae579f6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
