<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Delete Invoice Line</name>
   <tag></tag>
   <elementGuidId>13c5ba0c-e7a1-43c4-bf54-75b9c1430722</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_3Q</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='isc_3Q']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>684294dc-a91c-4923-a86c-b83701bddd56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_3Q</value>
      <webElementGuid>394356ae-76ec-4a46-b0af-8637dec0bbe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete Invoice Line</value>
      <webElementGuid>d9fa8864-6ef3-4bb7-b858-05b08e3cc7b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_3Q&quot;)</value>
      <webElementGuid>b3ee229c-93f8-4f10-a0c8-bf6ea7db1e58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_3Q']</value>
      <webElementGuid>c007a937-a963-4cdb-b117-7aacea78731c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_3R']/table/tbody/tr/td/div</value>
      <webElementGuid>b56a68cc-d172-433c-bb57-798b27bbc28c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export Excel'])[1]/following::div[4]</value>
      <webElementGuid>94f66191-f893-41f4-8d66-002a046f26eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete Billing Run'])[1]/following::div[6]</value>
      <webElementGuid>e864c95e-4fbe-46ba-abe6-7c82d7e69c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Invoice Line'])[1]/preceding::div[1]</value>
      <webElementGuid>db0bca4b-2a60-4659-8dac-607ae8602cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export Excel'])[2]/preceding::div[3]</value>
      <webElementGuid>b2250fad-b70f-4ac3-b7ec-4f72332ecd95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Delete Invoice Line']/parent::*</value>
      <webElementGuid>0de8e39e-5ad1-4611-9b2e-07e80d545ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/table/tbody/tr/td/div</value>
      <webElementGuid>80dc6d1b-797a-480e-b7dd-b571dc5cce44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_3Q' and (text() = 'Delete Invoice Line' or . = 'Delete Invoice Line')]</value>
      <webElementGuid>07bd29c7-0b05-40e1-959e-5a2c4c948880</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
