<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Edit Invoice Line</name>
   <tag></tag>
   <elementGuidId>0ca85638-d5e0-4735-9d94-3b2a459ebb7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_3O</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='isc_3O']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1ccaa28f-3f7d-4120-834a-e24cacd4b790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_3O</value>
      <webElementGuid>f98c3329-9209-4630-a445-b49e54896e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit Invoice Line</value>
      <webElementGuid>b2c1b117-2a9b-4799-b2d2-d86201fca5b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_3O&quot;)</value>
      <webElementGuid>9aa5d900-76e6-410f-ade2-9b47267b3c70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_3O']</value>
      <webElementGuid>7e045b71-be86-4ff5-874b-970d8ab12300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_3P']/table/tbody/tr/td/div</value>
      <webElementGuid>83465315-279d-4174-aaaa-9417b2a53add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete Invoice Line'])[1]/following::div[2]</value>
      <webElementGuid>1a0dadcf-f832-4f2d-aab9-cad442de5c89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export Excel'])[1]/following::div[6]</value>
      <webElementGuid>f1618446-c235-4721-b0b1-bb30885e9ec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export Excel'])[2]/preceding::div[1]</value>
      <webElementGuid>10568328-2112-4493-899a-dfbadd3c6498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Run Date'])[1]/preceding::div[7]</value>
      <webElementGuid>428ea087-cab7-4aa3-ad51-0ac632bb20df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit Invoice Line']/parent::*</value>
      <webElementGuid>b2ad4e56-1ba8-45c7-aa4b-50783225001d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/table/tbody/tr/td/div</value>
      <webElementGuid>e84bb91f-4e08-48bd-82fa-3685e060a430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_3O' and (text() = 'Edit Invoice Line' or . = 'Edit Invoice Line')]</value>
      <webElementGuid>254b01ca-998c-4fbc-8f2a-e233ecd8f348</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
