<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Add Billing Run</name>
   <tag></tag>
   <elementGuidId>3359e200-e1ba-424b-a451-c385dd41e4ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_3G</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='isc_3G']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6af86a39-83cd-4b9f-9d46-f33ec5bbeffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_3G</value>
      <webElementGuid>af61d96c-b39f-45dc-b623-1f831de98f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Billing Run</value>
      <webElementGuid>ad9190df-7b55-4bc4-b2cd-382f11399af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_3G&quot;)</value>
      <webElementGuid>4d614049-8d11-4b8d-ad5e-29f991c819b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_3G']</value>
      <webElementGuid>14e16af5-958d-4e56-9b36-7fd8fc18c56a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_3H']/table/tbody/tr/td/div</value>
      <webElementGuid>c79b375a-fb64-4179-944b-dad3146a8285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[3]/following::div[2]</value>
      <webElementGuid>bb76fc83-798d-429e-b994-aaba8bc76635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Bulk Billing / Invoicing (Basic &amp; Advanced)'])[1]/following::div[8]</value>
      <webElementGuid>89c049e8-8f16-4fe6-bbbf-1c4aa1d27fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete Billing Run'])[1]/preceding::div[1]</value>
      <webElementGuid>9c105df3-3e1f-4c7d-aa99-e29dd5fbc492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export Excel'])[1]/preceding::div[3]</value>
      <webElementGuid>1747565f-5285-4e4c-a705-cb2b5f24e6ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Billing Run']/parent::*</value>
      <webElementGuid>f2634374-2e74-4426-8297-5b81d6bc2062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td/div</value>
      <webElementGuid>bddaf6c0-3754-4038-9a40-ac9cfb56fa47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_3G' and (text() = 'Add Billing Run' or . = 'Add Billing Run')]</value>
      <webElementGuid>f9e5169c-e3dd-4eb6-b70d-05ff6c414fd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
