<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Delete Billing Run</name>
   <tag></tag>
   <elementGuidId>1ebe7a0a-292c-41e7-af10-2b35031a87bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_3I</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='isc_3I']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>02e53913-ed1d-4dab-8709-e4b084771e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_3I</value>
      <webElementGuid>a22bc0dc-4559-4305-8f68-cde69ac2947a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete Billing Run</value>
      <webElementGuid>6011c8d2-e91d-4cd9-8bf0-c4c6a1ceedb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_3I&quot;)</value>
      <webElementGuid>3f7792cd-19d8-4232-a1e9-6902e2e5fc59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_3I']</value>
      <webElementGuid>a4ad7102-1c1b-4624-b861-7c6af95dfb40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_3J']/table/tbody/tr/td/div</value>
      <webElementGuid>7453de12-5799-440a-b6bc-37e01d29612a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Billing Run'])[1]/following::div[2]</value>
      <webElementGuid>4ad58879-cb2a-443e-962e-4980b743299e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[3]/following::div[4]</value>
      <webElementGuid>fd86b9da-d4fe-4015-856d-f26d8dca4aa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export Excel'])[1]/preceding::div[1]</value>
      <webElementGuid>1d85b2f6-75dd-463e-9b5c-cf5b6bba81ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete Invoice Line'])[1]/preceding::div[3]</value>
      <webElementGuid>8f15e933-b29e-446b-a6a7-5a6b127492ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Delete Billing Run']/parent::*</value>
      <webElementGuid>71f3c821-a86f-4b69-894c-e6a94102ef48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr/td/div</value>
      <webElementGuid>43b9a36e-3da6-4bcd-9f4b-87df3cefd0a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_3I' and (text() = 'Delete Billing Run' or . = 'Delete Billing Run')]</value>
      <webElementGuid>7cd04157-7a9c-4adc-a1fc-41080f81392c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
