<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Export Excel</name>
   <tag></tag>
   <elementGuidId>f7cb4f6b-9621-4c7e-ae2b-4b67acdb72ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_3S</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='isc_3S']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1a1778f1-8493-4ef2-8ed1-ea5ae9938123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_3S</value>
      <webElementGuid>6bd93953-aff1-4d61-8bfa-067ce6ad4ff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Export Excel</value>
      <webElementGuid>a920b23f-4930-42c8-9051-a161a640aeb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_3S&quot;)</value>
      <webElementGuid>8a9f58b6-7be7-485d-be23-704dfe4215a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_3S']</value>
      <webElementGuid>377fd079-bed7-41ce-b990-5435da583834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_3T']/table/tbody/tr/td/div</value>
      <webElementGuid>bf9ac672-58c4-46ea-ad7e-991de7f3a1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Invoice Line'])[1]/following::div[2]</value>
      <webElementGuid>ad634aeb-ee9a-4cda-b979-e07e49222887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete Invoice Line'])[1]/following::div[4]</value>
      <webElementGuid>7b501446-937a-4e95-ac7d-e2085094a164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Run Date'])[1]/preceding::div[5]</value>
      <webElementGuid>b23cfd9f-2540-431b-ad4b-78785ed99844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice Date'])[1]/preceding::div[9]</value>
      <webElementGuid>21d794a4-fc0c-4ecc-a748-a345d0475a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/table/tbody/tr/td/div</value>
      <webElementGuid>36651f36-e235-420d-a84d-c3c6d2cf6154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_3S' and (text() = 'Export Excel' or . = 'Export Excel')]</value>
      <webElementGuid>31f4912f-c66c-48fb-a961-b50311f4aa72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
