<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Open a PROMPT box_debugTextbox</name>
   <tag></tag>
   <elementGuidId>47bd7973-d5f3-4433-b442-c713bf3654e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#debugTextbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='debugTextbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1044af43-e338-43df-bd5d-7a79a568f0e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8dce90cd-cd56-429e-aacb-9eca58157361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>debugTextbox</value>
      <webElementGuid>4dcd3fb7-4e0c-4276-ba98-6be6c6cf69c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;debugTextbox&quot;)</value>
      <webElementGuid>b963071b-5cfd-4834-9b6e-f73ecd89f5e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='debugTextbox']</value>
      <webElementGuid>bda3b4ba-580b-4396-917f-443ae73c87bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>40e20552-10b5-4b39-a63a-594a292a8ba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'debugTextbox']</value>
      <webElementGuid>a58c37f0-6cf1-43f0-a2bd-bbf38f4785cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
