<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_LOGIN_personalInfoFrame</name>
   <tag></tag>
   <elementGuidId>14a523a6-1632-4db3-bba8-1ea0c484acfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#personalInfoFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='personalInfoFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e4e5bd52-af8a-492a-9666-aec1bce8c2d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personalInfoFrame</value>
      <webElementGuid>ca0dc6ad-e0c5-497d-8989-9fcb227d3824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>learnks1-frame1.html</value>
      <webElementGuid>9fa71323-6dbf-42a5-a5d2-8b4d6b2eade5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>09272976-1f36-4032-998a-c821ee19a709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>125</value>
      <webElementGuid>4607edc4-9e07-4be7-8aa3-c7389f84c76e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personalInfoFrame&quot;)</value>
      <webElementGuid>cc5c24e8-c186-4651-b2b0-d8fa8b38db33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='personalInfoFrame']</value>
      <webElementGuid>08b943cc-7237-469f-a94f-f4d1b52fa9ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>6fe4a9c1-ba22-484c-85b2-3f66c8a0224d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'personalInfoFrame' and @src = 'learnks1-frame1.html']</value>
      <webElementGuid>b92eaa85-c1ee-4747-9a36-36fac9df2771</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
